/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componente;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author skyli
 */
public class battleField extends javax.swing.JPanel {

    /**
     * Creates new form battleField
     */
    public battleField() {
        initComponents();
        initSQM(9,9);
    }
    
    private void initSQM(int horizontal, int vertical){
        JPanel SQM;
        int posX = 0, posY = 0;
        
        for (int i = 1; i <= horizontal; i++){
            SQM = new JPanel();
            SQM.setName("i" + String.valueOf(i) + "j0");
            SQM.setSize(60,60);
            SQM.setLocation(posX, posY);
            SQM.setBackground(Color.blue);
            this.add(SQM);
            
            for (int j = 2; j <= vertical; j++){
                posY += 61;
                SQM = new JPanel();
                SQM.setName("i" + String.valueOf(i) + "j" + String.valueOf(j));
                SQM.setSize(60,60);
                SQM.setLocation(posX, posY);
                SQM.setBackground(Color.red);
                SQM.setVisible(true);
                this.add(SQM);                
            }            
            posX += 61;            
            posY = 0;
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
