/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componente;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author skyli
 */
public class battleField extends javax.swing.JPanel {

    /**
     * Creates new form battleField
     */
    private int matBattleField[][];

    public int[][] getMatBattleField() {
        return matBattleField;
    }

    public void setMatBattleField(int[][] matBattleField) {
        this.matBattleField = matBattleField;
    }
    
    public battleField() {
        initComponents();
        initSQM(12,9);
        inicializaMatriz();
    }
    
    private void inicializaMatriz(){
        this.setMatBattleField(new int[12][9]);
    }
    
    private void initSQM(int horizontal, int vertical){
        SQM sqmAux;
        int posX = 0, posY = 0, size;
        // seta tamanho dos blocos
        size = 30;       
        
        for (int i = 1; i <= horizontal; i++){
            sqmAux = new SQM();
            sqmAux.setPosX(i);
            sqmAux.setPosY(1);
            
            sqmAux.setSize(size,size);
            sqmAux.setLocation(posX, posY);
            sqmAux.setBackground(Color.green);
            this.add(sqmAux);
            
            for (int j = 2; j <= vertical; j++){
                posY += size + 1;
                sqmAux = new SQM();
                sqmAux.setPosX(i);
                sqmAux.setPosY(j);
            
                sqmAux.setSize(size,size);
                sqmAux.setLocation(posX, posY);
                sqmAux.setBackground(Color.green);
                sqmAux.setVisible(true);
                this.add(sqmAux);                
            }            
            posX += size + 1;            
            posY = 0;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
